# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:             [jekyll-sitemap, jekyll-gist, jekyll-seo-tag]
plugins:
  - jekyll-gist
  - jekyll-seo-tag

permalink:        pretty

# Setup
title:            Minima
tagline:          'A Bootstrap theme for GitHub Pages'
description:      'A Bootstrap theme for GitHub Pages'
baseurl:          /Minima
color:            DA2E75
navbar:           Default

# SEO Advanced usage
twitter:
  username:       rimeofficial
  card:           summary
facebook:
  app_id:         510262139040639
  publisher:      297545803726080
  admins:         suvozit
logo:             https://avatars1.githubusercontent.com/u/8429423?v=3&s=500
# google_site_verification: KT5gs8h0wvaagLKAVWq8bbeNwnZZK1r1XQysX3xurLU
author:           Rhyme Tek.
image:
  twitter:        https://avatars1.githubusercontent.com/u/8429423?v=3&s=500
  facebook:       https://avatars1.githubusercontent.com/u/8429423?v=3&s=500
  height:         500
  width:          500
social:
  name: Rhyme Tek.
  links:
    - https://twitter.com/RhymeTek
    - https://www.facebook.com/RhymeTek
    - https://www.linkedin.com/in/RhymeTek
    - https://github.com/RhymeTek
    - https://keybase.io/RhymeTek
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
lang: en_US

# Custom vars
version:          2.0.2

# Github vars
github:
  username:       RhymeTek

collections:
  pages:
    output:       true
    permalink:    /:path

defaults:
  - scope:
      path:       ''
      type:       pages
    values:
      layout:     pages

google_analytics: UA-41643154-1
blog:             rimeofficial.tumblr.com
