# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:             [jekyll-sitemap]

permalink:        pretty

# Setup
title:            Jelly Bean
description:      'A Theme for GitHub Pages'
baseurl:          /Jelly-Bean

# SEO Advanced usage
twitter:
  username:       rimeofficial
facebook:
  app_id:         510262139040639
  # publisher:      1234
  # admins:         1234
logo:             https://avatars1.githubusercontent.com/u/8429423?v=3&s=500
# google_site_verification: KT5gs8h0wvaagLKAVWq8bbeNwnZZK1r1XQysX3xurLU
author:           Rime
image:
  twitter:        https://avatars1.githubusercontent.com/u/8429423?v=3&s=500
  facebook:       https://avatars1.githubusercontent.com/u/8429423?v=3&s=500
  height:         500
  width:          500

# Custom vars
version:          2.0.0

# Github vars
github:
  username:       RhymeTek

collections:
  docs:
    output:       true
    permalink:    /:path

defaults:
  - scope:
      path:       ''
      type:       docs
    values:
      layout:     default

google_analytics: UA-41643154-1

app:
  name:           Rime
  url:            http://rime.co
