# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:             [jekyll-sitemap, jekyll-gist, jekyll-seo-tag]
plugins:
  - jekyll-gist
  - jekyll-seo-tag

permalink:        pretty

# Setup
title:            Minima
description:      'A Theme for GitHub Pages'
baseurl:          /Minima
color:            DA2E75
navbar:           Default

# SEO Advanced usage
twitter:
  username:       rimeofficial
facebook:
  app_id:         510262139040639
  # publisher:      1234
  # admins:         1234
logo:             https://avatars1.githubusercontent.com/u/8429423?v=3&s=500
# google_site_verification: KT5gs8h0wvaagLKAVWq8bbeNwnZZK1r1XQysX3xurLU
author:           Rhyme Tek.
image:
  twitter:        https://avatars1.githubusercontent.com/u/8429423?v=3&s=500
  facebook:       https://avatars1.githubusercontent.com/u/8429423?v=3&s=500
  height:         500
  width:          500

# Custom vars
version:          2.0.2

# Github vars
github:
  username:       RhymeTek

collections:
  pages:
    output:       true
    permalink:    /:path

defaults:
  - scope:
      path:       ''
      type:       pages
    values:
      layout:     default

google_analytics: UA-41643154-1
blog:             rimeofficial.tumblr.com
