# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:             [jekyll-gist, jekyll-sitemap, jekyll-seo-tag]

permalink:        pretty

# Setup
title:            Minimal
description:      'A Theme for GitHub Pages'
baseurl:          /jelly-bean

# SEO Advanced usage
twitter:
  username:       rimeofficial
facebook:
  app_id:         510262139040639
  # publisher:      1234
  # admins:         1234
logo:             http://rimeofficial.github.io/images/logo.png
# google_site_verification: KT5gs8h0wvaagLKAVWq8bbeNwnZZK1r1XQysX3xurLU
author:           Rime
image:
  twitter:        http://rimeofficial.github.io/images/twitter.png
  facebook:       http://rimeofficial.github.io/images/facebook.png
  height:         500
  width:          500

# Custom vars
version:          2.0.0

# Github vars
github:
  username:       RimeOfficial

collections:
  docs:
    output:       true
    permalink:    /:path

defaults:
  - scope:
      path:       ''
      type:       docs
    values:
      layout:     page

google_analytics: UA-41643154-1

app:
  title:          Rime
  home:           rime.co
  social:         rime
  blog:           rimeofficial.tumblr.com