# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist

permalink:        pretty

# Setup
title:            Minima
tagline:          'A Bootstrap theme for GitHub Pages'
description:      'A Bootstrap responsive two-column Jekyll documentation theme that pairs a prominent navbar with uncomplicated content.'
baseurl:          /Minima
color:            DA2E75
navbar:           Default

# jekyll-seo-tag
twitter:
  username:       RhymeTek_
  card:           summary
facebook:
  app_id:         510262139040639
  publisher:      297545803726080
  admins:         suvozit
logo:             /images/logo-share.png
author:           Rhyme Technologies
image:
  twitter:        /images/logo-share.png
  facebook:       /images/logo-share.png
  height:         500
  width:          500
social:
  name: Rime
  links:
    - https://twitter.com/RhymeTek_
    - https://www.facebook.com/RimeSocial
    - https://www.linkedin.com/company/Rhyme-Tek
    - https://github.com/RimeOfficial
    - https://keybase.io/RhymeTek
webmaster_verifications:
  google: KT5gs8h0wvaagLKAVWq8bbeNwnZZK1r1XQysX3xurLU
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
lang: en_UK

# jekyll-sitemap
defaults:
  - scope:
      path:            "assets/*"
    values:
      sitemap:         false

# Custom vars
version:          2.0.2

# Github vars
github:
  username:       RimeOfficial

collections:
  pages:
    output:       true
    permalink:    /:path

defaults:
  - scope:
      path:       ''
      type:       pages
    values:
      layout:     pages

google_analytics: UA-41643154-1
blog:             rimeofficial.tumblr.com
