# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:             
                  - jekyll-gist
                  - jekyll-sitemap

# Setup
title:            Jelly Bean
tagline:          'A Jekyll theme'
description:      'A slenderize two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> wiki theme that pairs a prominent sidebar with uncomplicated content.'
url:              http://wiki.rime.co
baseurl:          /jelly-bean

author:
  name:           'Rime'
  url:            https://rime.co

# Custom vars
version:          1.0.0

# Github vars
github:
  repo:           https://github.com/rimeofficial/jelly-bean

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page